import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ['vietnamese'], weight: ['100', '300']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookiesStore = cookies()
  const sessionToken = cookiesStore.get('sessionToken')
  // console.log('Root Layout: ',cookiesStore.get('sessionToken'))
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Toaster />
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

          <Header />
          <AppProvider initialSesseionToken = {sessionToken?.value}>
            {children}
          </AppProvider>
              
        </ThemeProvider>
      </body>
    </html>
  );
}
