import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Layout Login Page",
  description: "Generated by create next app",
};

export default function LayoutLogin({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="noto-sans-display" style={{backgroundColor: "#ff3"}}>
        {children}
      </body>
    </html>
  );
}
